configurationDefinitions:
  - platform: ALL
    description: myagent agent configuration, provided by the user
    type: agent-config
    version: 1.0.0
    format: yml
    schema: ./schemas/myagent-config.json
